In [1]:
import numpy

In [2]:
1

1

In [3]:
type(1)

int

In [4]:
2.73

2.73

In [5]:
type(2.73)

float

In [6]:
123**123

114374367934617190099880295228066276746218078451850229775887975052369504785666896446606568365201542169649974727730628842345343196581134895919942820874449837212099476648958359023796078549041949007807220625356526926729664064846685758382803707100766740220839267

In [7]:
'asd'

'asd'

In [9]:
l = [1, 2.3, 'asd', [1, 3.7]]

In [10]:
l

[1, 2.3, 'asd', [1, 3.7]]

In [11]:
l.append(3.14)

In [12]:
l

[1, 2.3, 'asd', [1, 3.7], 3.14]

In [13]:
l[2]

'asd'

In [14]:
# (value, next)
# value: valore da salvare
# next: puntatore alla prossima cella o null

In [16]:
t=(1, 2.3, 'asd')

In [19]:
l[2] = 'marco'

In [20]:
l

[1, 2.3, 'marco', [1, 3.7], 3.14]

In [21]:
t[1] = 'marco'

TypeError: 'tuple' object does not support item assignment

In [22]:
d={'a': 1, 'b': 3, 'c':10}

In [23]:
d

{'a': 1, 'b': 3, 'c': 10}

In [24]:
d['b']

3

In [25]:
d['d'] = 'statistica'

In [26]:
d

{'a': 1, 'b': 3, 'c': 10, 'd': 'statistica'}

In [27]:
d['e']

KeyError: 'e'

In [28]:
hash('e')

-4518538967429727753

In [29]:
hash('marco')

522802939678563345

In [33]:
hash([2,3,4])

TypeError: unhashable type: 'list'

In [35]:
d={[2,3]: 6, (5,3,2): 3}

TypeError: unhashable type: 'list'

In [39]:
hash('corso')

-3645253118881428248

In [40]:
hash(' di statistica')

-7098757725449361173

In [61]:
a=numpy.array([1.0,2,3,4,5], dtype='float32')

In [48]:
a.dtype

dtype('float32')

In [49]:
len(a)

5

In [50]:
len(l)

5

In [52]:
type(a.shape)

tuple

In [53]:
1,

(1,)

In [54]:
b=numpy.array([[1,2], [3,4], [5,6]])

In [55]:
len(b)

3

In [56]:
b.shape

(3, 2)

In [57]:
b[1][0]

3

In [58]:
b[1,0]

3

In [59]:
b[1]

array([3, 4])

In [60]:
b[1][0]

3

In [62]:
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [63]:
a[2]

3.0

In [64]:
a[1:3]

array([2., 3.], dtype=float32)

In [65]:
a[1:]

array([2., 3., 4., 5.], dtype=float32)

In [66]:
a[0:3]

array([1., 2., 3.], dtype=float32)

In [67]:
a[:3]

array([1., 2., 3.], dtype=float32)

In [69]:
b=a[:]

In [70]:
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [71]:
b

array([1., 2., 3., 4., 5.], dtype=float32)

In [72]:
a[0] = 0

In [73]:
a

array([0., 2., 3., 4., 5.], dtype=float32)

In [74]:
b

array([0., 2., 3., 4., 5.], dtype=float32)

In [75]:
c = a.copy()

In [78]:
numpy.random.normal(5, 1, (5,3))

array([[4.15589428, 4.53566094, 4.20553511],
       [5.72917429, 4.69796066, 4.36229367],
       [5.95108264, 5.3169447 , 5.74208233],
       [5.66753108, 5.88225379, 5.74147286],
       [5.06062549, 3.54052043, 5.2911908 ]])

In [85]:
l=numpy.random.normal(5, size=5000)

In [131]:
def likelihood(data, mu, sigma):
    like = numpy.exp(-(data - mu)**2 / (2*sigma**2)) / numpy.sqrt(2*numpy.pi*sigma**2)
    return numpy.prod(like)

def log_likelihood(data, mu, sigma):
    log_like = -(data - mu)**2 / (2*sigma**2) - numpy.log(2*numpy.pi*sigma**2) / 2
    return numpy.sum(log_like)

def log_prior

def log_evidence

def log_posterior

In [132]:
data = numpy.random.normal(5, 2, 1000)

In [134]:
log_likelihood(data, 5.0, 2.0)

-2089.384215121633

In [92]:
b = a + 5

In [93]:
b

array([ 5.,  7.,  8.,  9., 10.], dtype=float32)

In [94]:
a

array([0., 2., 3., 4., 5.], dtype=float32)

In [95]:
a*b

array([ 0., 14., 24., 36., 50.], dtype=float32)

In [97]:
c = numpy.exp(a) + numpy.log(b) + 2

In [99]:
a*b+c*a

array([  0.      ,  36.66993 ,  96.494934, 271.1815  , 813.57874 ],
      dtype=float32)

In [102]:
import math

In [103]:
math.exp(a)

TypeError: only size-1 arrays can be converted to Python scalars