# Libreria Numpy

Nella documentazione ufficiale:
- Quickstart, per iniziare a smanettare da subito: https://numpy.org/doc/stable/user/quickstart.html
- Tutorial più completo con approccio teorico: https://numpy.org/doc/stable/user/absolute_beginners.html 

In [3]:
import numpy as np

In [4]:
# Prima prova semplice

a = np.arange(10)
print(np.shape(a)) # equivalente a a.shape
print(a)
print(type(a))

a2 = a[:,np.newaxis]
print(a2)
print(a2.shape)

print(a[2])
print(a2[2,0])

(10,)
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
2
2


In [5]:
b = np.arange(10)
c = np.arange(10)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(type(a))

print('prendo un solo elemento nella posizione 1,1',a[1,1])
print('prendo la riga 0', a[0,:])
print('prendo la colonna 0',a[:,0])
print('è equivalente a prendere la riga 0 - numpy salva gli array row-wise',a[1])
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
prendo un solo elemento nella posizione 1,1 6
prendo la riga 0 [1 2 3 4]
prendo la colonna 0 [1 5 9]
è equivalente a prendere la riga 0 - numpy salva gli array row-wise [5 6 7 8]
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]


# Creare Array 

In [6]:
array_per_elementi = np.array([1,2,3,4]) # o la sua variante N-dimensionale
array_unitario = np.ones(6) # crea un array di 1 con dimensione 6
print(array_unitario)
matrice_unit = np.ones([6,6])
print(matrice_unit)

array_nullo = np.zeros(6) # crea un array di 0
print(array_nullo) 
# analogo per matrici come per ones

a = np.arange(1,20,2) 
print(a)

b = np.linspace(1,10,num=10) # unico caso in cui gli estremi sono entrambi inclusi
print(b)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0.]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [7]:
c = np.array([1,2,4,7,0,-3,-20,18],)
np.sort(c)

array([-20,  -3,   0,   1,   2,   4,   7,  18])

In [8]:
print(a+b)
d = np.concatenate((a,b))
d

[ 2.  5.  8. 11. 14. 17. 20. 23. 26. 29.]


array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
print(np.shape(matrice_unit))
print(np.ndim(matrice_unit)) # mi dice il numero di assi dell'array
print(np.size(matrice_unit)) # mi dice gli elementi totali

(6, 6)
2
36


In [10]:
a = np.arange(6)
#e = a.reshape(3,2)
e = np.reshape(a, (3,2))
print(e)

[[0 1]
 [2 3]
 [4 5]]


In [11]:
print(a[-3]) # con il "-" conta gli elementi dall'ultimo

3


In [12]:
a = np.arange(100)
print(a[(a>=10) & (a<20)])

[10 11 12 13 14 15 16 17 18 19]


In [13]:
a = np.array([0,0,4,3,0,2,1])
i = np.nonzero(a)
print(a[i])

[4 3 2 1]


# ATTENZIONE

In [14]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
b = a
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
b[0] = 99
print(b)

[99  1  2  3  4  5  6  7  8  9]


In [17]:
print(a)

[99  1  2  3  4  5  6  7  8  9]


In [18]:
# copia reale 
a = np.arange(10)
print(a)
b = a.copy()
#b = np.copy(a)
print(b)
b[0]=99
print(a,b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] [99  1  2  3  4  5  6  7  8  9]


In [19]:
#oppure, ma meno elegante
a = np.arange(10)
print(a)
b = np.zeros(len(a))
b[:]=a[:] # se non metto le parentesi quadre non creo una copia ma un puntatore
print(b)
b[0]=99
print(a,b)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9] [99.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


# Operazioni algebra lineare

In [20]:
a = np.random.uniform(0,1,10) # genera 10 numeri distribuiti in maniera uniforme tra 0 e 1
print(a)
B = np.random.normal(0,1,(10,10)) # genera una matrice 10x10 con valori distribuiti come una Normale  con var=1 e media 0
print(B)

[0.09135212 0.39353016 0.48665149 0.55521576 0.69298982 0.72242308
 0.93448766 0.18776886 0.02034483 0.66803699]
[[ 0.32485889  0.48510328 -0.46948319 -2.18001286 -0.15840845  0.20591334
   1.27541107 -1.32499819  0.69964673 -1.19088182]
 [ 0.83854391 -0.3048683  -0.01826392  0.5437595   0.76044048  0.48618481
  -0.74107541  0.46816268 -1.30843429  0.02781084]
 [ 0.76629716  0.79274846 -0.602198    1.46290443  1.06412286  0.01389085
  -0.25174974 -2.39901609  1.11386856 -1.86133042]
 [-1.14191984  1.80272675  0.3964008   1.77074814 -2.22735475 -0.02933406
   0.29969825 -2.9839157   1.2726251  -0.53997448]
 [ 0.50116775 -0.37741937 -0.32927896 -0.28656424  2.00149863  0.94944627
   0.29603189 -0.99623477 -0.1928169   0.31999811]
 [-0.55650866  1.03980385  0.10521334  1.27915484 -0.02775123 -0.31778319
   2.35393178  0.87562184 -0.33925571 -0.67893251]
 [-1.16285247 -0.6530008   1.19306701 -0.25244611 -0.49774501  0.08190731
   0.86747498  1.61854079 -0.01858923  0.84797104]
 [-0.7664664

In [21]:
a + B # somma il vettore colonna a tutte le righe della matrice
a * B # fa il prodotto element wise del vettore per la matrice 
a - B
a / B

array([[ 2.81205531e-01,  8.11229653e-01, -1.03656849e+00,
        -2.54684628e-01, -4.37470236e+00,  3.50838410e+00,
         7.32695274e-01, -1.41712538e-01,  2.90787183e-02,
        -5.60959940e-01],
       [ 1.08941362e-01, -1.29082019e+00, -2.66455052e+01,
         1.02106862e+00,  9.11300546e-01,  1.48590219e+00,
        -1.26098862e+00,  4.01076093e-01, -1.55489889e-02,
         2.40207398e+01],
       [ 1.19212390e-01,  4.96412397e-01, -8.08125377e-01,
         3.79529757e-01,  6.51231024e-01,  5.20071351e+01,
        -3.71197064e+00, -7.82691110e-02,  1.82650189e-02,
        -3.58902957e-01],
       [-7.99987112e-02,  2.18297179e-01,  1.22767535e+00,
         3.13548692e-01, -3.11126830e-01, -2.46274487e+01,
         3.11809520e+00, -6.29269979e-02,  1.59865071e-02,
        -1.23716401e+00],
       [ 1.82278520e-01, -1.04268671e+00, -1.47793072e+00,
        -1.93749145e+00,  3.46235472e-01,  7.60888845e-01,
         3.15671286e+00, -1.88478522e-01, -1.05513729e-01,
         2.

In [22]:
C = np.random.normal(0,1,(5,10))
print(C)
print(np.shape(C*a)) # moltiplicazione element wise

[[ 0.59175408  0.71404057  0.78584075 -1.80883303  0.23189446  2.39581476
   0.09709173 -0.31568715 -0.13754349 -0.28968131]
 [-0.33191377  0.01322863 -0.03344426  0.11030868  0.07163129  0.60278346
  -1.8441036  -0.97515209  0.49368645 -0.49259233]
 [ 0.79528316 -1.35340503  0.49192418 -0.22449988  1.09017904 -0.2412199
   0.11091598  0.75194198  0.33387413 -1.26219971]
 [-0.42271122  0.75384779 -0.42846574 -0.08061201 -0.19050394 -0.72003411
   1.08654583 -1.56960205 -0.89486087  0.7251959 ]
 [-0.36939477  0.7589973   0.48454626 -0.66794638  1.16209905  1.38940801
   0.77608085 -0.56738734 -0.30370095  0.38632638]]
(5, 10)


In [23]:
D = np.dot(C,a) # moltiplicazione riga per colonna (o np.matmul o @)
print(D)

[ 1.43982349 -1.72046249 -0.35554757  0.53948237  2.80955924]


$ a = a_\mu$ 

$ C = C^i_j$

$ D = C^i_j\cdot a_\mu = d_j $

In [24]:
E = np.dot(a,C.T) # array.T è equivalente a np.transpose(C)
print(E)

[ 1.43982349 -1.72046249 -0.35554757  0.53948237  2.80955924]


In [25]:
#trasposizione
C.T #metodo che restituisce la trasposta di C
np.transpose(C) # funzione equivalente

array([[ 0.59175408, -0.33191377,  0.79528316, -0.42271122, -0.36939477],
       [ 0.71404057,  0.01322863, -1.35340503,  0.75384779,  0.7589973 ],
       [ 0.78584075, -0.03344426,  0.49192418, -0.42846574,  0.48454626],
       [-1.80883303,  0.11030868, -0.22449988, -0.08061201, -0.66794638],
       [ 0.23189446,  0.07163129,  1.09017904, -0.19050394,  1.16209905],
       [ 2.39581476,  0.60278346, -0.2412199 , -0.72003411,  1.38940801],
       [ 0.09709173, -1.8441036 ,  0.11091598,  1.08654583,  0.77608085],
       [-0.31568715, -0.97515209,  0.75194198, -1.56960205, -0.56738734],
       [-0.13754349,  0.49368645,  0.33387413, -0.89486087, -0.30370095],
       [-0.28968131, -0.49259233, -1.26219971,  0.7251959 ,  0.38632638]])

In [26]:
b = np.random.uniform(1,10,10)
c = np.random.uniform(1,10,10)
print(b*c)
print(np.dot(b,c))

[11.15414293 31.82622476  9.62716962  5.5679765  35.12890501  3.89402218
 41.03766311 47.82636759 37.68007836 91.95696683]
315.6995169023859


In [27]:
a=np.array([1,2,3])
b=np.array([5,6,7])
(a+b)**2. - np.sqrt(a)

array([35.        , 62.58578644, 98.26794919])

In [29]:
a = np.array([[1,2],[3,4]],order='F')
a.flags['F_CONTIGUOUS']

True